mod max_consecutive_ones_485;
mod maximum_subarray_53;
mod majority_element_169;
mod jump_game;
mod maximum_length_substring_with_two_occurrences_3090;
mod best_time_to_buy_and_sell_stock;
mod move_zeroes_283;
